apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nodeapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: nodeapp-service
          servicePort: 80
